{{ config(
    materialized='table'
) }}
 
SELECT
    COUNT(*) AS ROW_COUNT,
    MAX(CREATED_AT) AS SNOWFLAKE_LAST_INSERT_TIME,
    CURRENT_TIMESTAMP() AS DBT_RUN_TIME,
 
    DATEDIFF(
        'second',
        MAX(CREATED_AT),
        CURRENT_TIMESTAMP()
    ) AS WAIT_TIME_SECONDS
 
FROM DBT_DB.CORE.ASTRO_TASK_TEST
